package main

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vnovick/itervox/internal/server"
)

func TestHeartbeatPathUsesWorkflowDirectory(t *testing.T) {
	dir := t.TempDir()
	workflowPath := filepath.Join(dir, "configs", "WORKFLOW.md")

	assert.Equal(t, filepath.Join(dir, "configs", ".itervox", "HEARTBEAT.md"), heartbeatPath(workflowPath))
}

func TestRenderHeartbeatIncludesRequiredSnapshotFields(t *testing.T) {
	now := time.Date(2026, 5, 21, 10, 0, 0, 0, time.UTC)
	unblockedAt := now.Add(-5 * time.Minute)
	snap := server.StateSnapshot{
		GeneratedAt:         now.Add(-time.Minute),
		Running:             []server.RunningRow{{Identifier: "ISS-1"}, {Identifier: "ISS-2"}},
		MaxConcurrentAgents: 5,
		TrackerKind:         "linear",
		ProjectName:         "Demo Project",
		AutomationQueueBackpressure: &server.AutomationQueueBackpressureRow{
			Length:          4,
			MaxLength:       100,
			Saturated:       true,
			PausedProducers: true,
		},
		DependencyAudit: []server.DependencyAuditRow{
			{Identifier: "ISS-1", Status: "blocked"},
			{Identifier: "ISS-2", Status: "unknown"},
			{Identifier: "ISS-3", Status: "unblocked", UnblockedAt: &unblockedAt},
		},
		InputRequired: []server.InputRequiredRow{{Identifier: "ISS-4"}},
		Retrying:      []server.RetryRow{{Identifier: "ISS-5", Error: "retry failed"}},
		ConfigInvalid: &server.ConfigInvalidStatus{Error: "WORKFLOW.md invalid"},
	}

	content := renderHeartbeat(snap, heartbeatOptions{
		WorkflowPath:  "/repo/WORKFLOW.md",
		SchemaVersion: 2,
		DashboardURL:  "http://127.0.0.1:8090/",
	}, now)

	for _, want := range []string{
		"# Itervox HEARTBEAT",
		"Generated: 2026-05-21T10:00:00Z",
		"Workflow: /repo/WORKFLOW.md",
		"Schema: 2",
		"Daemon: running",
		"Dashboard: http://127.0.0.1:8090/",
		"- Kind: linear",
		"- Project: Demo Project",
		"- Running: 2/5",
		"- Automation queue: 4/100",
		"- Producers paused: true",
		"- Saturated: true",
		"- Blocked: 1",
		"- Unknown: 1",
		"- Unblocked: 1",
		"- Recently unblocked: 1",
		"- Input required: 1",
		"- Retry queue: 1",
		"- Last error: WORKFLOW.md invalid",
		"Generated by itervox; do not edit.",
	} {
		assert.Contains(t, content, want)
	}
}

func TestRenderHeartbeatFallsBackToRetryError(t *testing.T) {
	now := time.Date(2026, 5, 21, 10, 0, 0, 0, time.UTC)
	content := renderHeartbeat(server.StateSnapshot{
		Retrying: []server.RetryRow{{Identifier: "ISS-1", Error: "agent failed"}},
	}, heartbeatOptions{}, now)

	assert.Contains(t, content, "- Last error: agent failed")
}

// gaps_11 G-15 / todolist6 P0-D — degraded startup is surfaced in the
// heartbeat as `Daemon: degraded` plus a `Last startup error:` line.
func TestRenderHeartbeatDegradedIncludesLastStartupError(t *testing.T) {
	now := time.Date(2026, 5, 21, 10, 0, 0, 0, time.UTC)

	content := renderHeartbeat(server.StateSnapshot{}, heartbeatOptions{
		StartupError: "see .itervox/STARTUP_ERROR.md (clear with `itervox doctor --clear-startup-error`)",
	}, now)

	assert.Contains(t, content, "Daemon: degraded")
	assert.Contains(t, content, "Last startup error: see .itervox/STARTUP_ERROR.md")
	assert.NotContains(t, content, "Daemon: running")
}

func TestRenderHeartbeatHealthyOmitsStartupErrorLine(t *testing.T) {
	now := time.Date(2026, 5, 21, 10, 0, 0, 0, time.UTC)

	content := renderHeartbeat(server.StateSnapshot{}, heartbeatOptions{}, now)

	assert.Contains(t, content, "Daemon: running")
	assert.NotContains(t, content, "Last startup error:")
	assert.NotContains(t, content, "Daemon: degraded")
}

// End-to-end over the real marker file: writeStartupErrorMarker → heartbeat
// degraded line; clearStartupErrorMarker → next write recovers to running.
func TestHeartbeatWriterReportsStartupErrorMarker(t *testing.T) {
	dir := t.TempDir()
	workflowPath := filepath.Join(dir, "WORKFLOW.md")
	writeStartupErrorMarker(workflowPath, errors.New("yaml: line 3: mixed indentation"))

	var writes []string
	writer := newHeartbeatWriter(heartbeatPath(workflowPath), heartbeatOptions{
		WorkflowPath: workflowPath,
	}, nil, time.Second)
	writer.writeFile = func(_ string, content string) error {
		writes = append(writes, content)
		return nil
	}

	now := time.Date(2026, 5, 21, 10, 0, 0, 0, time.UTC)
	require.NoError(t, writer.WriteNow(now))
	require.Len(t, writes, 1)
	assert.Contains(t, writes[0], "Daemon: degraded")
	assert.Contains(t, writes[0],
		"Last startup error: see "+filepath.Join(dir, ".itervox", "STARTUP_ERROR.md"))

	clearStartupErrorMarker(workflowPath)
	writer.Request()
	require.NoError(t, writer.MaybeWrite(now.Add(2*time.Second)))
	require.Len(t, writes, 2)
	assert.Contains(t, writes[1], "Daemon: running")
	assert.NotContains(t, writes[1], "Last startup error:")
}

func TestWriteHeartbeatCreatesParentAndWritesContent(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".itervox", "HEARTBEAT.md")

	require.NoError(t, writeHeartbeat(path, "heartbeat content\n"))

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, "heartbeat content\n", string(data))
}

func TestWriteHeartbeatUsesAtomicWriter(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".itervox", "HEARTBEAT.md")
	var called bool
	var gotPath string
	var gotContent string
	var gotPerm fs.FileMode
	original := heartbeatWriteFile
	heartbeatWriteFile = func(path string, data []byte, perm fs.FileMode) error {
		called = true
		gotPath = path
		gotContent = string(data)
		gotPerm = perm
		return errors.New("stop before disk write")
	}
	t.Cleanup(func() { heartbeatWriteFile = original })

	err := writeHeartbeat(path, "heartbeat content\n")

	require.Error(t, err)
	assert.True(t, called)
	assert.Equal(t, path, gotPath)
	assert.Equal(t, "heartbeat content\n", gotContent)
	assert.Equal(t, fs.FileMode(0o644), gotPerm)
}

func TestHeartbeatWriterThrottlesWrites(t *testing.T) {
	now := time.Date(2026, 5, 21, 10, 0, 0, 0, time.UTC)
	var writes []string
	writer := newHeartbeatWriter("HEARTBEAT.md", heartbeatOptions{}, func() server.StateSnapshot {
		return server.StateSnapshot{}
	}, 10*time.Second)
	writer.writeFile = func(_ string, content string) error {
		writes = append(writes, content)
		return nil
	}

	require.NoError(t, writer.WriteNow(now))
	writer.Request()
	require.NoError(t, writer.MaybeWrite(now.Add(time.Second)))
	require.Len(t, writes, 1)

	require.NoError(t, writer.MaybeWrite(now.Add(10*time.Second)))
	require.Len(t, writes, 2)
	assert.True(t, strings.Contains(writes[1], "Generated: 2026-05-21T10:00:10Z"))
}
