package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/vnovick/itervox/internal/atomicfs"
	"github.com/vnovick/itervox/internal/server"
)

const heartbeatMinInterval = 15 * time.Second

var heartbeatWriteFile = atomicfs.WriteFile

type heartbeatOptions struct {
	WorkflowPath  string
	SchemaVersion int
	DashboardURL  string
	// StartupError is a one-line pointer to .itervox/STARTUP_ERROR.md when a
	// previous startup failed. Non-empty flips `Daemon:` to `degraded` and
	// adds a `Last startup error:` line to the rendered heartbeat. Populated
	// per write via the writer's startupError getter so the line disappears
	// once the marker is cleared (gaps_11 G-15 / todolist6 P0-D).
	StartupError string
	// LastCrash is set for the first boot after the previous run crashed
	// (detected by armCrashOutput, CORE-007). Rendered as a single
	// "- Last crash:" line carrying ONLY the crash timestamp and the
	// crash.log path — never panic text, which bypasses log redaction.
	LastCrash crashReport
}

type heartbeatWriter struct {
	path        string
	options     heartbeatOptions
	snapshot    func() server.StateSnapshot
	minInterval time.Duration
	writeFile   func(path string, content string) error
	// startupError re-reads the STARTUP_ERROR.md marker on every write so
	// the heartbeat reports degraded while the marker exists and recovers as
	// soon as an operator clears it (`itervox doctor --clear-startup-error`).
	startupError func() string

	mu        sync.Mutex
	dirty     bool
	lastWrite time.Time
}

func heartbeatPath(workflowPath string) string {
	base := "."
	if strings.TrimSpace(workflowPath) != "" {
		base = filepath.Dir(workflowPath)
	}
	return filepath.Join(base, ".itervox", "HEARTBEAT.md")
}

func newHeartbeatWriter(path string, opts heartbeatOptions, snapshot func() server.StateSnapshot, minInterval time.Duration) *heartbeatWriter {
	if minInterval <= 0 {
		minInterval = heartbeatMinInterval
	}
	if snapshot == nil {
		snapshot = func() server.StateSnapshot { return server.StateSnapshot{} }
	}
	return &heartbeatWriter{
		path:         path,
		options:      opts,
		snapshot:     snapshot,
		minInterval:  minInterval,
		writeFile:    writeHeartbeat,
		startupError: func() string { return startupErrorSummary(opts.WorkflowPath) },
		dirty:        true,
	}
}

func (w *heartbeatWriter) Request() {
	w.mu.Lock()
	w.dirty = true
	w.mu.Unlock()
}

func (w *heartbeatWriter) WriteNow(now time.Time) error {
	if now.IsZero() {
		now = time.Now().UTC()
	}
	if err := w.writeAt(now.UTC()); err != nil {
		return err
	}
	w.mu.Lock()
	w.lastWrite = now.UTC()
	w.dirty = false
	w.mu.Unlock()
	return nil
}

func (w *heartbeatWriter) MaybeWrite(now time.Time) error {
	if now.IsZero() {
		now = time.Now().UTC()
	}
	now = now.UTC()
	w.mu.Lock()
	intervalElapsed := w.lastWrite.IsZero() || now.Sub(w.lastWrite) >= w.minInterval
	// v0.2.0 audit P2-3 — only write when something has actually changed
	// (`dirty`) AND the throttle interval has elapsed. The earlier gate
	// fired on the interval alone, causing spurious file-mtime churn that
	// file-watcher tools react to on every quiet tick.
	if !intervalElapsed || !w.dirty {
		w.mu.Unlock()
		return nil
	}
	w.mu.Unlock()

	// v0.2.0 audit P3-9 — advance lastWrite/clear dirty only on success.
	// The previous code advanced lastWrite before writeAt, so a transient
	// disk-full error extended the next retry by the full throttle
	// interval (15s by default) instead of letting the next tick try again
	// immediately.
	if err := w.writeAt(now); err != nil {
		return err
	}
	w.mu.Lock()
	w.dirty = false
	w.lastWrite = now
	w.mu.Unlock()
	return nil
}

func (w *heartbeatWriter) Run(ctx context.Context) {
	ticker := time.NewTicker(w.minInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case now := <-ticker.C:
			if err := w.MaybeWrite(now.UTC()); err != nil {
				slog.Warn("heartbeat: write failed", "path", w.path, "error", err)
			}
		}
	}
}

func (w *heartbeatWriter) writeAt(now time.Time) error {
	opts := w.options
	if w.startupError != nil {
		opts.StartupError = w.startupError()
	}
	return w.writeFile(w.path, renderHeartbeat(w.snapshot(), opts, now))
}

func renderHeartbeat(snap server.StateSnapshot, opts heartbeatOptions, now time.Time) string {
	if now.IsZero() {
		now = time.Now().UTC()
	}
	var b strings.Builder
	b.WriteString("# Itervox HEARTBEAT\n\n")
	b.WriteString("Generated by itervox; do not edit.\n\n")
	fmt.Fprintf(&b, "Generated: %s\n", now.UTC().Format(time.RFC3339))
	if opts.WorkflowPath != "" {
		fmt.Fprintf(&b, "Workflow: %s\n", opts.WorkflowPath)
	}
	if opts.SchemaVersion != 0 {
		fmt.Fprintf(&b, "Schema: %d\n", opts.SchemaVersion)
	}
	// gaps_11 G-15 / todolist6 P0-D — a present STARTUP_ERROR.md marker means
	// the last startup failed; report degraded plus a pointer line until the
	// operator clears the marker.
	if strings.TrimSpace(opts.StartupError) != "" {
		b.WriteString("Daemon: degraded\n")
		fmt.Fprintf(&b, "Last startup error: %s\n", opts.StartupError)
	} else {
		b.WriteString("Daemon: running\n")
	}
	dashboard := opts.DashboardURL
	if dashboard == "" {
		dashboard = "disabled"
	}
	fmt.Fprintf(&b, "Dashboard: %s\n", dashboard)
	if !snap.GeneratedAt.IsZero() {
		fmt.Fprintf(&b, "Snapshot: %s\n", snap.GeneratedAt.UTC().Format(time.RFC3339))
	}

	b.WriteString("\n## Tracker\n")
	fmt.Fprintf(&b, "- Kind: %s\n", fallbackText(snap.TrackerKind, "unknown"))
	fmt.Fprintf(&b, "- Project: %s\n", fallbackText(snap.ProjectName, "unknown"))

	queueLength, queueMax, saturated, paused := heartbeatQueueStats(snap)
	b.WriteString("\n## Capacity\n")
	fmt.Fprintf(&b, "- Running: %d/%d\n", len(snap.Running), snap.MaxConcurrentAgents)
	fmt.Fprintf(&b, "- Automation queue: %d/%d\n", queueLength, queueMax)
	fmt.Fprintf(&b, "- Producers paused: %t\n", paused)
	fmt.Fprintf(&b, "- Saturated: %t\n", saturated)

	blocked, unknown, unblocked, recent := heartbeatDependencyCounts(snap, now)
	b.WriteString("\n## Dependency Audit\n")
	fmt.Fprintf(&b, "- Blocked: %d\n", blocked)
	fmt.Fprintf(&b, "- Unknown: %d\n", unknown)
	fmt.Fprintf(&b, "- Unblocked: %d\n", unblocked)
	fmt.Fprintf(&b, "- Recently unblocked: %d\n", recent)
	// critical-path-ordering Task 5: only shown once non-zero, matching the
	// rest of the heartbeat's "don't clutter the file with empty sections"
	// convention (e.g. the StartupError line above).
	if n := len(snap.DependencyCycles); n > 0 {
		fmt.Fprintf(&b, "- Cycles: %d\n", n)
	}
	if n := len(snap.DependencyAttention); n > 0 {
		fmt.Fprintf(&b, "- Attention: %d\n", n)
	}

	// CORE-055 — agent backend circuit breakers (not the tracker budget).
	b.WriteString("\n## Backends\n")
	if len(snap.BackendHealth) == 0 {
		b.WriteString("- none reported\n")
	}
	for _, r := range snap.BackendHealth {
		b.WriteString(heartbeatBackendLine(r) + "\n")
	}
	if n := len(snap.AutoSwitches); n > 0 {
		fmt.Fprintf(&b, "- Auto-switched issues: %d\n", n)
	}

	b.WriteString("\n## Attention\n")
	fmt.Fprintf(&b, "- Input required: %d\n", len(snap.InputRequired))
	fmt.Fprintf(&b, "- Retry queue: %d\n", len(snap.Retrying))
	// outbox Task 4 — pending/degraded counts, shown only when non-zero
	// (matches the Cycles/Attention/StartupError "don't clutter a healthy
	// heartbeat" convention above). An issue a human moved out of active
	// states while a write was pending can't auto-reconcile (see
	// docs/configuration.md's tracker.outbox row) — a persistently nonzero
	// degraded count here is the signal an operator should check the
	// Outbox panel and Discard any stuck entries.
	if pending := len(snap.OutboxEntries); pending > 0 {
		fmt.Fprintf(&b, "- Outbox pending: %d\n", pending)
		if degraded := outboxDegradedCount(snap.OutboxEntries); degraded > 0 {
			fmt.Fprintf(&b, "- Outbox degraded: %d\n", degraded)
		}
	}
	fmt.Fprintf(&b, "- Last error: %s\n", heartbeatLastError(snap))
	if !opts.LastCrash.At.IsZero() {
		fmt.Fprintf(&b, "- Last crash: %s (full dump: %s)\n",
			opts.LastCrash.At.UTC().Format(time.RFC3339), opts.LastCrash.Path)
	}
	return b.String()
}

func heartbeatQueueStats(snap server.StateSnapshot) (length int, maxLength int, saturated bool, paused bool) {
	if snap.AutomationQueueBackpressure != nil {
		bp := snap.AutomationQueueBackpressure
		return bp.Length, bp.MaxLength, bp.Saturated, bp.PausedProducers
	}
	return len(snap.AutomationQueue), 0, false, false
}

// heartbeatDependencyCounts derives the "## Dependency Audit" summary
// counts. Blocked is the union of two sources, deduplicated by identifier
// (issue #50 M2):
//   - DependencyAuditRow.Status == "blocked" — tracker-declared blockers;
//   - DependencyGraphEdgeRow with Origin == "inferred" && Gating == true —
//     issues held solely by an LLM-inferred edge, which previously had no
//     DependencyAudit row at all and so were silently dropped from this
//     count.
//
// Unknown/Unblocked/RecentlyUnblocked are unaffected — those states only
// exist on the tracker-sourced DependencyAudit rows.
func heartbeatDependencyCounts(snap server.StateSnapshot, now time.Time) (blocked int, unknown int, unblocked int, recentlyUnblocked int) {
	blockedIDs := make(map[string]struct{})
	for _, row := range snap.DependencyAudit {
		switch row.Status {
		case "blocked":
			blockedIDs[row.Identifier] = struct{}{}
		case "unknown":
			unknown++
		case "unblocked":
			unblocked++
			if row.UnblockedAt != nil && !row.UnblockedAt.IsZero() && now.Sub(*row.UnblockedAt) <= 24*time.Hour {
				recentlyUnblocked++
			}
		}
	}
	for _, edge := range snap.DependencyGraphEdges {
		if edge.Origin == "inferred" && edge.Gating {
			blockedIDs[edge.TargetIdentifier] = struct{}{}
		}
	}
	return len(blockedIDs), unknown, unblocked, recentlyUnblocked
}

// outboxDegradedCount counts how many outbox entry rows crossed the
// operator-visible-error-badge threshold (server.OutboxEntryRow.Degraded).
func outboxDegradedCount(entries []server.OutboxEntryRow) int {
	count := 0
	for _, e := range entries {
		if e.Degraded {
			count++
		}
	}
	return count
}

// heartbeatLastError picks the single most operator-relevant error, in
// priority order: an invalid WORKFLOW.md, the last tracker failure (CORE-044:
// a poll outage or rate limit, or a failed failed-state move), the degraded
// outbox entry that failed most recently (a stuck tracker write), then the
// retry queue and the automation queue.
func heartbeatLastError(snap server.StateSnapshot) string {
	if snap.ConfigInvalid != nil && strings.TrimSpace(snap.ConfigInvalid.Error) != "" {
		return snap.ConfigInvalid.Error
	}
	if e := snap.LastTrackerError; e != nil {
		return formatTrackerErrorLine(e)
	}
	if e := newestDegradedOutboxEntry(snap.OutboxEntries); e != nil {
		return fmt.Sprintf("outbox %s %s degraded: %s", e.Kind, e.Identifier, e.LastError)
	}
	for _, row := range snap.Retrying {
		if strings.TrimSpace(row.Error) != "" {
			return row.Error
		}
	}
	for _, row := range snap.AutomationQueue {
		if strings.TrimSpace(row.ErrorMessage) != "" {
			return row.ErrorMessage
		}
	}
	return "none"
}

// formatTrackerErrorLine renders a TrackerErrorRow as one HEARTBEAT line,
// e.g. "tracker poll outage (3 consecutive) at <RFC3339>: <message>".
func formatTrackerErrorLine(e *server.TrackerErrorRow) string {
	var b strings.Builder
	fmt.Fprintf(&b, "tracker %s %s", e.Op, e.Kind)
	if e.ConsecutiveFailures > 1 {
		fmt.Fprintf(&b, " (%d consecutive)", e.ConsecutiveFailures)
	}
	if e.ResetAt != nil {
		fmt.Fprintf(&b, " until %s", e.ResetAt.UTC().Format(time.RFC3339))
	}
	fmt.Fprintf(&b, " at %s: %s", e.At.UTC().Format(time.RFC3339), singleLine(e.Message))
	return b.String()
}

// newestDegradedOutboxEntry returns the degraded entry with the greatest
// LastFailedAt, or nil when none is degraded.
func newestDegradedOutboxEntry(entries []server.OutboxEntryRow) *server.OutboxEntryRow {
	var best *server.OutboxEntryRow
	for i := range entries {
		e := &entries[i]
		if !e.Degraded {
			continue
		}
		if best == nil || failedAt(e).After(failedAt(best)) {
			best = e
		}
	}
	return best
}

func failedAt(e *server.OutboxEntryRow) time.Time {
	if e.LastFailedAt == nil {
		return time.Time{}
	}
	return *e.LastFailedAt
}

// singleLine keeps a multi-line error from breaking HEARTBEAT's one-line
// list item.
func singleLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func writeHeartbeat(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("heartbeat: create %s: %w", filepath.Dir(path), err)
	}
	if err := heartbeatWriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("heartbeat: write %s: %w", path, err)
	}
	return nil
}

func fallbackText(value string, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}
