#!/usr/bin/env bash
#
# CORE-113 test for deploy/monitoring/heartbeat-metrics.sh. Run: make deploy-test.
# Uses ITERVOX_METRICS_DRY_RUN=1 (no cloud call) and the prometheus textfile mode.
#
# Proves:
#   - every HEARTBEAT.md label the script parses is still written by
#     cmd/itervox/heartbeat.go / snapshot_backends.go (drift guard: a renamed
#     line in the writer fails here instead of silently reading 0);
#   - a full fixture yields outbox_pending=3, outbox_degraded=1, deps_cycles=1,
#     deps_unknown=2, backends_limited=1, degraded=1, last_crash=1 and the
#     capacity/queue split, each with a non-empty instance label;
#   - a minimal fixture (the zero-valued lines omitted, as the writer does)
#     yields 0 for each omitted series instead of failing;
#   - --instance overrides the host name; prometheus mode writes the textfile.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPT="$HERE/heartbeat-metrics.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

fails=0
pass() { printf 'ok   %s\n' "$*"; }
fail() { printf 'FAIL %s\n' "$*"; fails=$((fails + 1)); }

# ── drift guard against the writer ──────────────────────────────────────────
WRITER="$ROOT/cmd/itervox/heartbeat.go"
if [[ -f "$WRITER" ]]; then
  missing=""
  for label in 'Running' 'Automation queue' 'Producers paused' 'Saturated' 'Blocked' 'Unknown' \
               'Unblocked' 'Recently unblocked' 'Cycles' 'Attention' 'Auto-switched issues' \
               'Input required' 'Retry queue' 'Outbox pending' 'Outbox degraded' 'Last crash'; do
    grep -qF "\"- $label: " "$WRITER" || missing+=" '$label'"
  done
  grep -qF '"Daemon: degraded\n"' "$WRITER" || missing+=" 'Daemon: degraded'"
  grep -qF '"\n## Backends\n"' "$WRITER" || missing+=" '## Backends'"
  grep -qF '"- %s: %s", name, r.Status' "$ROOT/cmd/itervox/snapshot_backends.go" || missing+=" 'backend line'"
  if [[ -z "$missing" ]]; then
    pass "every parsed HEARTBEAT.md label is still emitted by cmd/itervox/heartbeat.go"
  else
    fail "labels no longer written by the daemon:$missing"
  fi
else
  echo "skip drift guard (no Go tree next to deploy/)"
fi

cat > "$WORK/full.md" <<'EOF'
# Itervox HEARTBEAT

Generated by itervox; do not edit.

Generated: 2026-09-27T10:00:00Z
Workflow: /srv/itervox/proj/WORKFLOW.md
Schema: 2
Daemon: degraded
Last startup error: config: tracker.kind missing
Dashboard: http://127.0.0.1:8090
Snapshot: 2026-09-27T10:00:00Z

## Tracker
- Kind: linear
- Project: proj

## Capacity
- Running: 2/4
- Automation queue: 5/100
- Producers paused: false
- Saturated: true

## Dependency Audit
- Blocked: 4
- Unknown: 2
- Unblocked: 7
- Recently unblocked: 1
- Cycles: 1
- Attention: 3

## Backends
- claude: limited until 2026-09-27T11:00:00Z (usage_limit)
- codex@build-1:22: probing (probe ENG-9)
- claude@build-1:22: ok
- Auto-switched issues: 2

## Attention
- Input required: 1
- Retry queue: 6
- Outbox pending: 3
- Outbox degraded: 1
- Last error: tracker: poll failed
- Last crash: 2026-09-27T09:00:00Z (full dump: /x/crash.log)
EOF

cat > "$WORK/min.md" <<'EOF'
# Itervox HEARTBEAT

Daemon: running
Dashboard: disabled

## Capacity
- Running: 0/2
- Automation queue: 0/0
- Producers paused: false
- Saturated: false

## Dependency Audit
- Blocked: 0
- Unknown: 0
- Unblocked: 0
- Recently unblocked: 0

## Backends
- none reported

## Attention
- Input required: 0
- Retry queue: 0
- Last error: none
EOF

series() { # series OUTPUT NAME -> value
  sed -nE "s/^itervox_heartbeat_$2\{instance=\"[^\"]+\"\} ([0-9]+)$/\1/p" <<<"$1"
}

OUT="$(ITERVOX_METRICS_DRY_RUN=1 bash "$SCRIPT" --heartbeat "$WORK/full.md" --instance vm-a)"
bad=""
for kv in running=2 capacity=4 queue_depth=5 queue_max=100 saturated=1 producers_paused=0 \
          deps_blocked=4 deps_unknown=2 deps_unblocked=7 deps_recently_unblocked=1 deps_cycles=1 \
          deps_attention=3 backends_limited=1 backends_probing=1 auto_switched=2 input_required=1 \
          retry_queue=6 outbox_pending=3 outbox_degraded=1 degraded=1 last_crash=1; do
  got="$(series "$OUT" "${kv%%=*}")"
  [[ "$got" == "${kv#*=}" ]] || bad+=" ${kv%%=*}=${got:-missing}(want ${kv#*=})"
done
if [[ -z "$bad" ]]; then
  pass "full fixture: outbox_pending=3 cycles=1 unknown=2 backends_limited=1 degraded=1 last_crash=1 (21 series)"
else
  fail "full fixture:$bad"
fi
if [[ "$(grep -c '^itervox_heartbeat_' <<<"$OUT")" == "$(grep -c '{instance="vm-a"}' <<<"$OUT")" ]]; then
  pass "every series carries instance=\"vm-a\""
else
  fail "instance label missing on some series"
fi
printf '%s\n' "$OUT" | grep -E 'outbox_pending|deps_cycles|deps_unknown' | grep -v '^#' | sed 's/^/     /'

OUT="$(ITERVOX_METRICS_DRY_RUN=1 bash "$SCRIPT" --heartbeat "$WORK/min.md")"
bad=""
for k in outbox_pending outbox_degraded deps_cycles deps_attention auto_switched backends_limited \
         backends_probing degraded last_crash; do
  [[ "$(series "$OUT" "$k")" == 0 ]] || bad+=" $k=$(series "$OUT" "$k")"
done
if [[ -z "$bad" ]] && grep -qE '^itervox_heartbeat_running\{instance="[^"]+"\} 0$' <<<"$OUT"; then
  pass "minimal fixture: omitted lines read as 0; default instance label non-empty ($(hostname))"
else
  fail "minimal fixture:$bad"
fi

TF="$WORK/itervox.prom"
bash "$SCRIPT" --cloud prometheus --heartbeat "$WORK/full.md" --instance vm-b --textfile "$TF"
if grep -q '^itervox_heartbeat_outbox_pending{instance="vm-b"} 3$' "$TF" && [[ -z "$(find "$WORK" -name 'itervox.prom.*')" ]]; then
  pass "prometheus mode writes the node_exporter textfile atomically (no temp left)"
else
  fail "textfile: $(head -3 "$TF" 2>/dev/null)"
fi

if [[ $fails -gt 0 ]]; then
  echo "heartbeat-metrics_test: $fails FAILED"
  exit 1
fi
echo "heartbeat-metrics_test: PASS"
